const List<String> availableSkills = [
  'Mobile Development',
  'Web Development',
  'Backend Development',
  'Frontend Development',
  'UI/UX Design',
  'Database Design',
  'Cloud Computing',
  'DevOps',
  'Machine Learning',
  'Artificial Intelligence',
  'Data Science',
  'Cybersecurity',
  'Game Development',
  'IoT Development',
  'Blockchain',
  'Software Architecture',
  'Project Management',
  'Technical Writing',
  'Testing & QA',
  'System Administration',
];
