name: utb_codebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  # Storage & Security
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Network
  http: ^1.1.0

  # Utils
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  intl: ^0.19.0
  image_network: ^2.5.6
  url_launcher: ^6.3.1
  infinite_scroll_pagination: ^4.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/asset/banner.png
    - lib/asset/logo.png
    - lib/asset/Profile.png
    - lib/asset/service1.png
    - lib/asset/service2.png
