// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfT26idc5iwfQYDaDkTtAgCDmzo9lqJWs',
    appId: '1:461474201195:web:34a18dbac9e2f82ab77b2e',
    messagingSenderId: '461474201195',
    projectId: 'utbcodebase',
    authDomain: 'utbcodebase.firebaseapp.com',
    storageBucket: 'utbcodebase.appspot.com',
    measurementId: 'G-ZNH7F1B0SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDowT6tm6JWUq1Utny2xTG8C33RAinUsG8',
    appId: '1:461474201195:android:61835fc2e19b1537b77b2e',
    messagingSenderId: '461474201195',
    projectId: 'utbcodebase',
    storageBucket: 'utbcodebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfq_JN2Id5jrMGA-sFn_QROzICuZO-dcg',
    appId: '1:461474201195:ios:cf36026922652009b77b2e',
    messagingSenderId: '461474201195',
    projectId: 'utbcodebase',
    storageBucket: 'utbcodebase.appspot.com',
    iosBundleId: 'com.example.codebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfq_JN2Id5jrMGA-sFn_QROzICuZO-dcg',
    appId: '1:461474201195:ios:cf36026922652009b77b2e',
    messagingSenderId: '461474201195',
    projectId: 'utbcodebase',
    storageBucket: 'utbcodebase.appspot.com',
    iosBundleId: 'com.example.codebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfT26idc5iwfQYDaDkTtAgCDmzo9lqJWs',
    appId: '1:461474201195:web:3de09523a4302069b77b2e',
    messagingSenderId: '461474201195',
    projectId: 'utbcodebase',
    authDomain: 'utbcodebase.firebaseapp.com',
    storageBucket: 'utbcodebase.appspot.com',
    measurementId: 'G-SDDH5E5Q52',
  );
}
